/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Error descriptor.
 */
export type ErrorIot_manager = {
  /**
   * Description of the error.
   */
  error?: string;
  /**
   * Request ID passed with the request X-Men-Requestid header or generated by the server.
   */
  request_id?: string;
};
