/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Error descriptor.
 */
export type ErrorReporting = {
  /**
   * Description of the error.
   */
  error?: string;
  /**
   * Request ID passed with the request X-MEN-RequestID header or generated by the server.
   */
  request_id?: string;
};
