module.exports = {
  SET_DEPLOYMENT_RELEASE: 'SET_DEPLOYMENT_RELEASE',
  CREATE_DEPLOYMENT: 'CREATE_DEPLOYMENT',
  REMOVE_DEPLOYMENT: 'REMOVE_DEPLOYMENT',
  RECEIVE_DEPLOYMENT: 'RECEIVE_DEPLOYMENT',
  RECEIVE_DEPLOYMENT_STATS: 'RECEIVE_DEPLOYMENT_STATS',
  RECEIVE_DEPLOYMENT_DEVICE_LOG: 'RECEIVE_DEPLOYMENT_DEVICE_LOG',
  RECEIVE_DEPLOYMENT_DEVICES: 'RECEIVE_DEPLOYMENT_DEVICES',
  RECEIVE_DEPLOYMENTS: 'RECEIVE_DEPLOYMENTS',
  RECEIVE_PENDING_DEPLOYMENTS: 'RECEIVE_PENDING_DEPLOYMENTS',
  RECEIVE_INPROGRESS_DEPLOYMENTS: 'RECEIVE_INPROGRESS_DEPLOYMENTS',
  RECEIVE_FINISHED_DEPLOYMENTS: 'RECEIVE_FINISHED_DEPLOYMENTS',
  RECEIVE_PENDING_DEPLOYMENTS_COUNT: 'RECEIVE_PENDING_DEPLOYMENTS_COUNT',
  RECEIVE_INPROGRESS_DEPLOYMENTS_COUNT: 'RECEIVE_INPROGRESS_DEPLOYMENTS_COUNT',
  RECEIVE_FINISHED_DEPLOYMENTS_COUNT: 'RECEIVE_FINISHED_DEPLOYMENTS_COUNT',
  SELECT_DEPLOYMENT: 'SELECT_DEPLOYMENT'
};
