module.exports = {
  ARTIFACTS_REMOVED_ARTIFACT: 'ARTIFACTS_REMOVED_ARTIFACT',
  ARTIFACTS_SET_ARTIFACT_URL: 'ARTIFACTS_SET_ARTIFACT_URL',
  RECEIVE_ARTIFACTS: 'RECEIVE_ARTIFACTS',
  UPLOAD_ARTIFACT: 'UPLOAD_ARTIFACT',
  UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',
  UPDATED_ARTIFACT: 'UPDATED_ARTIFACT',
  RECEIVE_RELEASES: 'RECEIVE_RELEASES'
};
