FROM cypress/included:6.2.0
WORKDIR /e2e
ENV CI=1
RUN curl -SL --fail "https://mender.s3-accelerate.amazonaws.com/temp_master/core-image-full-cmdline-qemux86-64.ext4" \
  -o core-image-full-cmdline-qemux86-64.ext4 && \
  curl -SL --fail -P cypress/fixtures "https://dgsbl4vditpls.cloudfront.net/mender-demo-artifact.mender" \
  -o mender-demo-artifact.mender && \
  curl -SL --fail "https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/master/mender-artifact" \
  -o /usr/bin/mender-artifact && \
  chmod +x /usr/bin/mender-artifact
COPY package.json package-lock.json cypress.json ./
RUN npm ci
COPY cypress ./cypress
RUN npx cypress verify
ENTRYPOINT []
CMD tail -f /dev/null
