FROM mendersoftware/mender-client-docker:master
RUN mkdir -p /run/dbus && apt-get -qqy update && apt-get -qqy install \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common
RUN curl -fLsS https://downloads.mender.io/repos/debian/gpg | apt-key add - && add-apt-repository \
  "deb [arch=amd64] https://downloads.mender.io/repos/debian experimental main"
RUN apt-get -qqy -o Dpkg::Options::=--force-confnew install mender-connect
COPY artifact_info /etc/mender/artifact_info
COPY clientEntrypoint.sh /entrypoint.sh
COPY device_type /var/lib/mender/device_type
COPY mender-connect.json /etc/mender/mender-connect.conf
