/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type AutoAuthRequest = {
  /**
   * Vendor-specific JSON representation of the device identity data (MACs, serial numbers, etc.).
   */
  id_data: string;
  /**
   * The device's public key (PEM encoding), generated by the device or pre-provisioned by the vendor. Currently supported public algorithms are: RSA, ED25519 and ECDSA.
   */
  pubkey: string;
  /**
   * Tenant token.
   */
  tenant_token?: string;
  /**
   * External identity which can be used to verify devices managed by cloud providers.
   * Currently, only Azure IoT Edge devices are supported.
   */
  external_id?: string;
};
